export const DataBoxDummy = [
    {
      dataId: 1,
      title: "Amendment to MP2014 Rail Station Text",
      subtitle: "Annotation of MRT and LRT station name.",
      num: 2,
      type: ["JSON", "KML"],
      from: "Urban Redevelopment Authority (URA)",
    },
    {
      dataId: 2,
      title: "Amendment to MP2014 Road Name",
      subtitle: "Annotation of road names.",
      num: 2,
      type: "JSON",
      from: "Urban Redevelopment Authority (URA)",
    },
    {
      dataId: 3,
      title: "Amendment to MP2014 Building",
      subtitle: "Indicative polygon representing building footprints.",
      num: 2,
      type: "JSON",
      from: "Urban Redevelopment Authority (URA)",
    },
    {
      dataId: 4,
      title: "Nature Reserves Gazette 2005",
      subtitle: "Gazetted land parcels details of the four nature reserves of Singapore under The Parks and Trees Act 2005. These land lot parcels were digitally capturedin 1995, and checked against SLA dataset obtained from the Land System Support Unit then.The lots' details were again updated and verifie…",
      num: 2,
      type: "JSON",
      from: "National Parks Board (NPARKS)",
    },
    {
      dataId: 5,
      title: "Coastal and Marine Habitat Map of Singapore 2010/2011",
      subtitle: "Mangrove forests, seagrass meadows and coral reefs are three of the most important coastal habitats of the world. Mangroves not only provide valuable ecosystems services such as coastal erosion protection, water filtration and the areas for fish and shrimp breeding, they also harvested as…",
      num: 2,
      type: "JSON",
      from: "National Parks Board (NPARKS)",
    },
  ];